spring:
  jpa:
    show-sql: false
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain
    min-response-size: 512

logging:
  level:
    pl.fireacademy: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
